# fly.toml app configuration file generated for towncivic on 2026-08-31T21:23:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'towncivic'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  S3_REGION = 'auto'
  TOWNCIVIC_ACCOUNTS = 'supabase'
  TOWNCIVIC_BASE_URL = 'https://towncivic.fly.dev'
  TOWNCIVIC_DOCUMENTS = 's3'
  TOWNCIVIC_SECURE_COOKIES = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    path = '/healthz'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
